# -*- coding: utf-8 -*-
"""Twitter Sentiment Analysis using Ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQdYzt-Kx6tOQ44eUEUspeR179hXgk0p
"""

#installing kaggle library
!pip install kaggle

#upload your kaggle api key
import os
os.environ['KAGGLE_API_TOKEN'] = 'KGAT_ac9df80f4fc2204a19d5ad99bca21fd4'

"""Importing Twitter Sentiment Dataset"""

!kaggle datasets download -d kazanova/sentiment140

# Extracting the compressed datset

from zipfile import ZipFile
dataset = '/content/sentiment140.zip'

with ZipFile(dataset,'r') as zip: #r is for read , zip is temporary name of zip file that we want to extract.
  zip.extractall()
  print('The dataset is extracted')

"""Importing the Dependencies"""

import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import nltk
nltk.download('stopwords')

#printing the stopwords of english
print(stopwords.words('english'))

# loading the data from csv file to pandas dataframe
twitter_data = pd.read_csv('/content/training.1600000.processed.noemoticon.csv', encoding = 'ISO-8859-1')

# checking the number of rows and columns
twitter_data.shape

# printing the first 5 rows of dataframe
twitter_data.head()

# naming the columns and reading the dataset again

column_names = ['target', 'ids', 'date', 'flag', 'user', 'text']
twitter_data = pd.read_csv('/content/training.1600000.processed.noemoticon.csv', encoding = 'ISO-8859-1', names = column_names)

twitter_data.shape

twitter_data.head()

#counting the number of missing values in the dataset in each column
twitter_data.isnull().sum()

# checking the distribution of target column
twitter_data['target'].value_counts()

"""Convert the positive target value "4" to "1"
"""

twitter_data.replace({'target':{4:1}}, inplace=True) # inplace = true for changing in original dataset

# checking the distribution of target column
twitter_data['target'].value_counts()

"""0 ---> Negative Tweet

1 ---> Positive Tweet

**Stemming**

Stemming is the process of converting word into base form by removing suffixes values

example : actor , acrtess , acting = act
"""

port_stem = PorterStemmer()

stop_words = set(stopwords.words('english'))

def stemming(content):
  stemmed_content = re.sub('[^a-zA-Z]',' ',content) # content = tweet , ^ = remove word if word not contain a-zA-Z alphabets ****
  stemmed_content = stemmed_content.lower()
  stemmed_content = stemmed_content.split() # split words based on whitespace
  stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stop_words]
  stemmed_content = ' '.join(stemmed_content) # join words together
  return stemmed_content

"""Creating new column stemmed content"""

twitter_data['stemmed_content'] = twitter_data['text'].apply(stemming) # 50 minutes to complete this operation

twitter_data.head()

print(twitter_data['stemmed_content'])

print(twitter_data['target'])

# sepearating the data and label
X = twitter_data['stemmed_content'].values # data
Y = twitter_data['target'].values # label

print(X)

print(Y)

"""Splitting the data to training data and test data"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2)
# 0.2 means test data is 20% and rest 80% is training data.
# stratify means negative and positive equally distribute. trainging and testing both contain 80:20 % ratio.

print(X.shape , X_train.shape, X_test.shape)

print(X_train)

print(X_test)

# converting the textual data to numerical data

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

print(X_train)

print(X_test)

"""Training the Machine Learning Model

Logistic Regression
"""

model = LogisticRegression(max_iter = 1000)

model.fit(X_train, Y_train)

"""Model Evaluation

Accuracy Score
"""

# Accuracy score on the training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score( Y_train, X_train_prediction)

print("Accuracy Score on the training data: ", training_data_accuracy)

# Accuracy score on the test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score( Y_test, X_test_prediction)

print("Accuracy Score on the training data: ", test_data_accuracy)

"""Model Accuracy = 77.6 %

Saving the trained model
"""

import pickle

filename = 'trained_model.sav'
pickle.dump(model, open(filename, 'wb')) # wb means writing and creating new file b means writing in binary file

"""Using the saved model for future predictions"""

# loading the saved model
loaded_model = pickle.load(open('/content/trained_model.sav', 'rb')) # rb means reading and creating new file b means reading in binary file

X_new = X_test[200]
print(Y_test[200])

prediction = loaded_model.predict(X_new)
print(prediction)

if (prediction[0] == 0):
  print('The tweet is negative')
else:
  print('The tweet is positive')

X_new = X_test[3]
print(Y_test[3])

prediction = loaded_model.predict(X_new)
print(prediction)

if (prediction[0] == 0):
  print('The tweet is negative')
else:
  print('The tweet is positive')